---
- hosts: proxmox_hosts
  strategy: free
  tasks:
    - name: create_windows_server
      when: "'primary_proxmox_host' in group_names" 
      include_role: 
        name: create_windows_server
      vars:
        vm_hostname: DC01
        static_ip: yes
        ip_address: 10.0.30.2
        ipv4_prefix: 24
        default_gateway: 10.0.30.1
        dns_1: 10.0.30.2
        dns_2: 1.1.1.1
        deploy_image: Windows Server 2022 SERVERSTANDARDCORE
        vm_admin_pass: "{{domain_controller_password}}"
        vm_memory_mb: 1024
        vm_cores: 1
        vm_sockets: 1
        start_at_boot: yes
    
    - name: create_windows_server
      when: "'secondary_proxmox_host' in group_names"
      include_role: 
        name: create_windows_server
      vars:
        vm_hostname: DC02
        static_ip: yes
        ip_address: 10.0.30.3
        ipv4_prefix: 24
        default_gateway: 10.0.30.1
        dns_1: 10.0.30.2
        dns_2: 1.1.1.1
        deploy_image: Windows Server 2022 SERVERSTANDARDCORE
        vm_admin_pass: "{{domain_controller_password}}"
        vm_memory_mb: 1024
        vm_cores: 1
        vm_sockets: 1
        start_at_boot: yes

    - name: create_windows_server
      when: "'primary_proxmox_host' in group_names" 
      include_role: 
        name: create_windows_server
      vars:
        vm_hostname: MGMT1
        static_ip: yes
        ip_address: 10.0.30.5
        ipv4_prefix: 24
        default_gateway: 10.0.30.1
        dns_1: 10.0.30.2
        dns_2: 10.0.30.3
        vm_admin_pass: "{{ management_host_1_password }}"
        vm_memory_mb: 4096
        vm_cores: 4
        vm_sockets: 1
        start_at_boot: yes


    - name: create_windows_server
      when: "'secondary_proxmox_host' in group_names" 
      include_role: 
        name: create_windows_server
      vars:
        vm_hostname: CONN01
        static_ip: yes
        ip_address: 10.0.30.21
        ipv4_prefix: 24
        default_gateway: 10.0.30.1
        dns_1: 10.0.30.2
        dns_2: 10.0.30.3
        deploy_image: Windows Server 2022 SERVERSTANDARD
        vm_admin_pass: "{{ conn01_password }}"
        vm_memory_mb: 2048
        vm_cores: 1
        vm_sockets: 1
        start_at_boot: yes

    - name: create_windows_server
      when: "'primary_proxmox_host' in group_names" 
      include_role: 
        name: create_windows_server
      vars:
        vm_hostname: PKI01
        static_ip: yes
        ip_address: 10.0.30.10
        ipv4_prefix: 24
        default_gateway: 10.0.30.1
        dns_1: 10.0.30.2
        dns_2: 10.0.30.3
        deploy_image: Windows Server 2022 SERVERSTANDARDCORE
        vm_admin_pass: "{{pki01_password}}"
        vm_memory_mb: 1024
        vm_cores: 1
        vm_sockets: 1
        start_at_boot: no
    
    - name: create_windows_server
      when: "'secondary_proxmox_host' in group_names"
      include_role: 
        name: create_windows_server
      vars:
        vm_hostname: PKI02
        static_ip: yes
        ip_address: 10.0.30.11
        ipv4_prefix: 24
        default_gateway: 10.0.30.1
        dns_1: 10.0.30.2
        dns_2: 10.0.30.3
        deploy_image: Windows Server 2022 SERVERSTANDARDCORE
        vm_admin_pass: "{{pki02_password}}"
        vm_memory_mb: 1024
        vm_cores: 1
        vm_sockets: 1
        start_at_boot: yes
    
    - name: create_windows_server
      when: "'primary_proxmox_host' in group_names"
      include_role: 
        name: create_windows_server
      vars:
        vm_hostname: SCCM01
        static_ip: yes
        ip_address: 10.0.30.15
        ipv4_prefix: 24
        default_gateway: 10.0.30.1
        dns_1: 10.0.30.2
        dns_2: 10.0.30.3
        deploy_image: Windows Server 2022 SERVERSTANDARD
        vm_admin_pass: "{{sccm01_password}}"
        vm_memory_mb: 8092
        vm_cores: 2
        vm_sockets: 1
        start_at_boot: yes
