---
- hosts: proxmox_hosts
  strategy: free
  tasks:
    - name: create_windows_server
      when: "'primary_proxmox_host' in group_names" 
      include_role: 
        name: create_windows_server
      vars:
        vm_hostname: MGMT1
        static_ip: yes
        ip_address: 10.0.30.5
        ipv4_prefix: 24
        default_gateway: 10.0.30.1
        dns_1: 10.0.30.2
        dns_2: 10.0.30.3
        deploy_image: Windows Server 2022 SERVERSTANDARD
        vm_admin_pass: "{{ management_host_1_password }}"
        vm_memory_mb: 4096
        vm_cores: 4
        vm_sockets: 1
        start_at_boot: yes

- hosts: management_hosts
  vars:
    ou_name: Management
  roles:
    - member_server
