---
# Get next available Proxmox VE VMID, semi-random, idempotent, seed from hostname & vm_hostname
- name: Get available VMID
  vars:
    var_concat_seed: "{{inventory_hostname}}-{{vm_hostname}}"
    rand_vmid: "{{9999 | random(seed=var_concat_seed)}}"  
  command: pvesh get /cluster/nextid -vmid {{rand_vmid}}
  register: next_vmid
  ignore_errors: true

- name: Creating Windows Server
  when: next_vmid.rc == 0
  block:
    # Create temp directory
    - name: Create temp directory
      file:
        path: /tmp/{{vm_hostname}}
        state: directory
    
    # Template out autounattend answer file
    - name: Template out autounattend answer file
      template:
        src: "{{role_path}}/templates/autounattend.xml.tpl"
        dest: /tmp/{{vm_hostname}}/autounattend.xml
    
    # Copy drivers & scripts for ISO
    - name: Copy files for ISO
      copy:
        src: "{{role_path}}/files/"
        dest: /tmp/{{vm_hostname}}/
    
    # Create ISO with drivers, scripts, & answer file    
    - name: Create ISO file
      become: true
      command: "genisoimage -J -r -o /var/lib/vz/template/iso/{{vm_hostname}}Provision.iso /tmp/{{vm_hostname}}/"
      register: iso_created
    
    # Create VM
    - name: Create VM
      command: "qm create {{next_vmid.stdout}} --name {{vm_hostname}} --sockets {{vm_sockets}} --cores {{vm_cores}} --memory {{vm_memory_mb}} --ide2 file={{os_iso_location}},media=cdrom --ide3 file=local:iso/{{vm_hostname}}Provision.iso,media=cdrom --net0 model=virtio,bridge=vmbr0,firewall=1,tag={{vlan}} --scsihw virtio-scsi-pci --scsi0 {{pve_storage_id}}:{{drive_size_gb}},format={{format}} --ostype {{vm_os_type}} --agent {{agent}}"
    
    # Start VM
    - name: Start VM
      command: "qm start {{next_vmid.stdout}}"
    
    # Wait for VM build
    - name: Wait for OS install, config, update. Up to 120 min. Monitor status if possible.
      command: "qm wait {{next_vmid.stdout}}"
      async: 7200
      poll: 30  
    
    # Remove CD drives
    - name: Remove IDE CD Drives
      command: "qm set {{next_vmid.stdout}} --delete ide2 --delete ide3"
    
    # Remove ISO
    - name: Remove Unattend ISO file
      file:
        path: /var/lib/vz/template/iso/{{vm_hostname}}Provision.iso
        state: absent
    
    # Cleanup temp files
    - name: Cleanup temp files used for ISO build
      file:
        path: /tmp/{{vm_hostname}}
        state: absent
      when: iso_created.changed      
    
    # Start VM
    - name: Start VM
      command: "qm start {{next_vmid.stdout}}"
    
    # set start on boot
    - name: Set Start On Boot
      command: "qm set {{next_vmid.stdout}} --onboot 1"
      when: start_at_boot

    - name: Done
      debug:
        msg: Server build {{vm_hostname}}, with VMID {{next_vmid.stdout}} complete.
