---
- name: Install Active Directory Domain Services
  win_feature: 
    name: AD-Domain-Services
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: adds_install

- name: Reboot when ADDS feature requires it
  win_reboot:
  when: adds_install.reboot_required

- name: Setup Domain Controller
  microsoft.ad.domain_controller:
    dns_domain_name: jordanfromit.fun
    domain_admin_user: JFIT\sa_ansible
    domain_admin_password: "{{ ansible_service_account_password }}"
    safe_mode_password: "{{ safe_mode_password }}"
    state: domain_controller
    reboot: true
